<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../../lib/Filter/Fail/Exception.php';

/**
 * Test class for Filter_Fail_Exception.
 * Generated by PHPUnit on 2010-05-06 at 11:56:35.
 */
class Filter_Fail_ExceptionTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Filter_Fail_Exception
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Filter_Fail_Exception;
	}



	public function testType() {
		$this->assertTrue($this->object instanceof Exception);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}
}
?>
