<?php

require_once dirname(__FILE__).'/../../../lib/Card/Exception.php';

/**
 * Test class for Card_Exception.
 * Generated by PHPUnit on 2010-05-06 at 08:46:07.
 */
class Card_ExceptionTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Card_Exception
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Card_Exception;
	}

	public function testType() {
		$this->assertTrue($this->object instanceof Exception);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}
}
?>
