<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../lib/Filter.php';

class MockFilter extends Filter {
	public function attempt(Card $old, Card $new) {
		throw new Filter_Exception();
	}
}

/**
 * Test class for Filter.
 * Generated by PHPUnit on 2010-05-06 at 08:46:07.
 */
class FilterTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Filter
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new MockFilter;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @expectedException Filter_Exception
	 */
	public function testTest() {
		$cards = array(new Card('C', 1));
		$new_cards = array(new Card('C', 2));

		$this->object->test($cards, $new_cards);


	}
}
?>
