<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../lib/Stack.php';

/**
 * Test class for Stack.
 * Generated by PHPUnit on 2010-05-06 at 08:46:06.
 */
class StackTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Stack
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Stack;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @todo Implement testAddFilter().
	 */
	public function testAddFilter() {
		
	}

	/**
	 * @todo Implement testDisableFilters().
	 */
	public function testDisableFilters() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testEnableFilters().
	 */
	public function testEnableFilters() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testAdd().
	 */
	public function testAdd() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPop().
	 */
	public function testPop() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCards().
	 */
	public function testGetCards() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}
}
?>
