<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../../lib/Filter/Chain/Or.php';

/**
 * Test class for Filter_Or.
 * Generated by PHPUnit on 2010-05-12 at 10:32:19.
 */
class Filter_Chain_OrTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Filter_Or
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Filter_Chain_Or;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @dataProvider dataTest
	 */
	public function testTest(array $old, array $new) {
		$this->object->addFilter(new Filter_Fail());
		$this->object->addFilter(new Filter_Pass());

		$this->assertTrue($this->object->test($old, $new));
	}

	/**
	 * @expectedException Filter_Fail_Exception
	 * @dataProvider dataTest
	 */
	public function testTestFail(array $old, array $new) {
		$this->object->addFilter(new Filter_Fail());
		$this->object->addFilter(new Filter_Fail());

		$this->object->test($old, $new);
	}

	/**
	 * @dataProvider dataTest
	 */
	public function testTestPass(array $old, array $new) {
		$this->object->addFilter(new Filter_Pass());

		$this->assertTrue($this->object->test($old, $new));
	}

	public function dataTest() {
		$r = array();
		$r[] = array(array(new Card('C', 1), new Card('D', 13)), array(new Card('C', 1), new Card('D', 13)));

		return $r;
	}
}
?>
