<?php

require_once dirname(__FILE__).'/../../../../lib/Filter/Chain/And.php';

class Filter_Chain_And_Proxy extends Filter_Chain_And {
	public function attempt(Card $old, Card $new) {
		return parent::attempt($old, $new);
	}
}

/**
 * Test class for Filter_And.
 * Generated by PHPUnit on 2010-05-07 at 09:20:29.
 */
class Filter_Chain_AndTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Filter_And
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Filter_Chain_And_Proxy;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @expectedException Filter_Fail_Exception
 * @dataProvider dataTest
	 */
	public function testTest(array $old, array $new) {
		$this->object->addFilter(new Filter_Fail());
		$this->object->addFilter(new Filter_Pass());

		$this->object->test($old, $new);
	}

	/**
	 * @dataProvider dataTest
	 */
	public function testTestPass(array $old, array $new) {
		$this->object->addFilter(new Filter_Pass());

		$this->assertTrue($this->object->test($old, $new));
	}

	public function dataTest() {
		$r = array();
		$r[] = array(array(new Card('C', 1), new Card('D', 13)), array(new Card('C', 1), new Card('D', 13)));

		return $r;
	}
}
?>
