<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for Filter_BeginsWithKing.
 * Generated by PHPUnit on 2010-05-06 at 11:06:50.
 */
class Filter_BeginsWithKingTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Filter_BeginsWithKing
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Filter_BeginsWithKing;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testTest().
     */
    public function testTest()
    {
		$c1 = array(new Card('C', 13));
		$c2 = array(new Card('C', 1));

		$this->assertTrue($this->object->test($c1, $c2));
    }

	public function testTestMultiple() {
		$c1 = array(new Card('C', 13), new Card('C', 12), new Card('H', 4));
		$c2 = array(new Card('D', 13), new Card('S', 12), new Card('C', 4));

		$this->assertTrue($this->object->test($c1, $c2));
	}


	/**
     * @expectedException Filter_BeginsWithKing_Exception
     */
	public function testTestMultipleFailure() {
		$c1 = array(new Card('C', 1), new Card('C', 12), new Card('H', 4));
		$c2 = array(new Card('D', 13), new Card('S', 12), new Card('C', 4));

		$this->assertTrue($this->object->test($c1, $c2));
	}

    /**
     * @expectedException Filter_BeginsWithKing_Exception
     */
    public function testTestFailure()
    {
		$c1 = array(new Card('C', 1));
		$c2 = array(new Card('C', 13));

		$this->object->test($c1, $c2);
    }

    /**
     * @todo Implement testAttempt().
     */
    public function testAttempt()
    {
		$c1 = new Card('C', 1);
		$c2 = new Card('C', 2);
		$this->assertEquals($this->object->attempt($c1, $c2), null);
    }
}
?>
