<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../lib/Filter/Fail.php';

/**
 * Test class for Filter_Fail.
 * Generated by PHPUnit on 2010-05-06 at 11:56:42.
 */
class Filter_FailTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Filter_Fail
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Filter_Fail;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @expectedException Filter_Fail_Exception
	 */
	public function testAttempt() {
		$this->object->attempt(new Card('C', 1), new Card('C', 3));
	}
}
?>
