<?php

/**
 * Test class for Filter_Ascending.
 * Generated by PHPUnit on 2010-05-06 at 11:06:49.
 */
class Filter_AscendingTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Filter_Ascending
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Filter_Ascending;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * This should work :)
     */
    public function testAttempt()
    {
		$cards_1 = new Card('C', 1);
		$cards_2 = new Card('C', 2);

		$this->assertTrue($this->object->attempt($cards_1, $cards_2) === null);
    }


    /**
     * This should not work
	 * @expectedException Filter_Ascending_Exception
     */
    public function testAttemptFailure()
    {
		$cards_1 = new Card('C', 2);
		$cards_2 = new Card('C', 1);

		$this->assertTrue($this->object->attempt($cards_1, $cards_2));
    }
}
?>
