<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for Filter_Sequential.
 * Generated by PHPUnit on 2010-05-06 at 11:06:50.
 */
class Filter_SequentialTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Filter_Sequential
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Filter_Sequential;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testAttempt().
     */
    public function testAttemptUp()
    {
		$c1 = new Card('C', 3);
		$c2 = new Card('D', 4);

		$this->assertEquals($this->object->attempt($c1, $c2), null);
    }

    /**
     * @todo Implement testAttempt().
     */
    public function testAttemptDown()
    {
		$c1 = new Card('C', 4);
		$c2 = new Card('D', 3);

		$this->assertEquals($this->object->attempt($c1, $c2), null);
    }

	/**
     * @expectedException Filter_Sequential_Exception
     */
    public function testAttemptFail()
    {
		$c1 = new Card('C', 5);
		$c2 = new Card('D', 3);

		$this->object->attempt($c1, $c2);
    }


}
?>
