<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../lib/Filter/Chain.php';

class Filter_Chain_Proxy extends Filter_Chain {
	public function attempt(Card $old, Card $new) {
		return parent::attempt($old, $new);
	}
}

/**
 * Test class for Filter_Chain.
 * Generated by PHPUnit on 2010-05-12 at 10:38:56.
 */
class Filter_ChainTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Filter_Chain
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Filter_Chain_Proxy;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @todo Implement testAddFilter().
	 */
	public function testAddFilter() {
		$this->object->addFilter(new Filter_Fail());
		$this->assertEquals($this->object->getFilters(), array(new Filter_Fail()));
	}

	public function testGetFilter() {
		$this->assertEquals($this->object->getFilters(), array());
	}

	public function testAttempt() {
		$this->assertTrue($this->object->attempt(new Card('C', 1), new Card('C', 2)));
	}
}
?>
