<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for Filter_BeginsWith1.
 * Generated by PHPUnit on 2010-05-06 at 11:06:49.
 */
class Filter_BeginsWith1Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var Filter_BeginsWith1
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Filter_BeginsWith1;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testTest().
     */
    public function testAttempt()
    {
		$card = new Card('C', 1);
		$card_2 = new Card('C', 2);

		$this->assertEquals($this->object->attempt($card, $card_2), null);
    }

    /**
     * This should work :)
     */
    public function testAttemptSuccess()
    {
		$cards_1 = array(new Card('C', 1));
		$cards_2 = array(new Card('C', 2));

		$this->assertTrue($this->object->test($cards_1, $cards_2));
    }


    /**
     * This should not work
	 * @expectedException Filter_BeginsWith1_Exception
     */
    public function testAttemptFailure()
    {
		$cards_1 = array(new Card('C', 2));
		$cards_2 = array(new Card('C', 1));

		$this->assertTrue($this->object->test($cards_1, $cards_2));
    }

	public function testAttemptMultipleSuccess() {
		$cards_1 = array(new Card('C', 1), new Card('C', 3), new Card('D', 12));
		$cards_2 = array(new Card('D', 13), new Card('H', 4));

		$this->assertTrue($this->object->test($cards_1, $cards_2));
	}


	/**
	 * @expectedException Filter_BeginsWith1_Exception
	 */
	public function testAttemptMultipleFailure() {
		$cards_1 = array(new Card('C', 4), new Card('C', 3), new Card('D', 3));
		$cards_2 = array(new Card('H', 2), new Card('H', 4));

		$this->assertTrue($this->object->test($cards_1, $cards_2));
	}
}
?>
